### ISSUE TITLE
Needs A Section To Add Manual Revision To Bash Config For 'code' CLI Command

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-0-macos-env-system#10]
### Canvas Link

https://learning.flatironschool.com/courses/5282/pages/macos-system-setup?module_item_id=349364

### Concern

This section should include the manual revision to your '~/.bashrc' if anyone who is more technically inclined wants to do this so that they can run 'code .' from terminal to open up VS Code.

This is more for people like myself who already have custom Bash configs via '~/.bashrc' that are used across Linux and on MacOS etc.

### Suggested Changes

Add a section like the following:

From this VS Code Docs page:
https://code.visualstudio.com/docs/setup/mac

Related Command To Add 'code' Command Manually To Bash Config:
```
cat << EOF >> ~/.bash_profile
# Add Visual Studio Code (code)
export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
EOF
```

**Comment by lizbur10** [comment]
Hi @SamuelBanya ! Thanks for the suggestion! The instructions already include how to set this up using the VS Code Command Palette, so I suspect manual instructions probably wouldn't be helpful for most students. 

Appreciate your interest in contributing to the curriculum! 💙
