### ISSUE TITLE
Inconsistency in the MacOS System Setup Module

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-0-macos-env-system#12]
### Canvas Link

https://learning.flatironschool.com/courses/6150/pages/macos-system-setup?module_item_id=482701

### Concern

There is an inconsistency between the instructions in the audio of the video and the text of the module:

Text in module:

> If your computer does not meet the requirements listed above, but you can upgrade, we recommend that you do so before completing the environment setup.

Audio in video (0:42 timestamp):

> If your computer doesn't meet those requirements but you can upgrade, we recommend holding off on that upgrade until after you've completed the environment setup.

This can be confusing for a beginner, especially since it is right at the beginning of the course.

**Comment by lizbur10** [comment]
Hi @codified45 ! Thanks for bringing this to our attention! The video has now be re-recorded and the inconsistency fixed. 

Thanks for contributing to the Flatiron School curriculum 💙
