### ISSUE TITLE
Installing Homebrew for M1 Macs

### ISSUE THREAD

**Issue by skywalkerATX** [learn-co-curriculum/phase-0-macos-env-system#8]
### Canvas Link

https://learning.flatironschool.com/courses/5290/pages/macos-system-setup?module_item_id=356872

### Concern

For M1 Macs (like my laptop) you need to run:

$ arch -x86_64 zsh

Before installing homebrew otherwise, Homebrew will fail to install. Many people may be running M1 chipped Macs now. 

### Suggested Changes

Add:

$ arch -x86_64 zsh  #Do this only for M1 Macs. 

Just above:

Type /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" and press <Enter>

**Comment by lizbur10** [comment]
Hi @skywalkerATX ! Thanks for bringing this to our attention. The instructions have been updated to include the troubleshooting information.

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by skywalkerATX** [comment]
Glad to help!
